---

- hosts: localhost
  connection: local
  tasks:

  - name: Coding Challenge
    community.docker.docker_compose:
      project_name: Coding-Challenge
      definition:
        version: '3'
        services:
           openresty:
             image: openresty/openresty:focal
             container_name: openresty
             ports:
               - "9000:80"
             networks:
               - Youcan-network
             restart: always
           nginx:
             build: /Users/anaselkassimi/Desktop/Coding-Challenge2/nginx
             image: nginx
             container_name: nginx
             ports:
               - "80:80"
             networks:
               - Youcan-network
             volumes:
               - coding-challenge:/usr/share/nginx/html
             restart: always
             depends_on:
               - php
           php:
             image: php:7.4-fpm
             container_name: php
             networks:
               - Youcan-network
             volumes:
               - coding-challenge:/usr/share/nginx/html
             restart: always
        volumes:
           coding-challenge:
             driver: local
             driver_opts:
               type: none
               device: "/Users/anaselkassimi/Desktop/Coding-Challenge2/volumes/"
               o: bind
        networks:
           Youcan-network:
             name: Youcan-network
             driver: bridge
