---

- hosts: localhost
  connection: local
  tasks:

  - name: Coding Challenge
    community.docker.docker_compose:
      project_name: Coding-Challenge
      definition:
        version: '3'
        services:
           nginx:
             build: /Users/anaselkassimi/Desktop/Coding-Challenge2/nginx
             image: nginx
             container_name: nginx
             ports:
               - "80:80"
            #  volumes:
            #    - html-volume:/usr/share/nginx/html
             networks:
               - Youcan-network
             restart: always
             depends_on:
               - openresty
           openresty:
             build: /Users/anaselkassimi/Desktop/Coding-Challenge2/openresty
             image: openresty
             container_name: openresty
             ports:
               - "8080:8080"
             volumes:
               - html-volume:/usr/local/openresty/nginx/html
             networks:
               - Youcan-network
             restart: always
             depends_on:
                - php
           php:
             image: php:7.4-fpm
             container_name: php
             networks:
               - Youcan-network
             volumes:
               - html-volume:/var/www/html
             restart: always
        volumes:
           html-volume:
             driver: local
             driver_opts:
               type: none
               device: "/Users/anaselkassimi/Desktop/Coding-Challenge2/volumes/html"
               o: bind        
        networks:
           Youcan-network:
             name: Youcan-network
             driver: bridge
